{
  "openapi": "3.0.0",
  "info": {
    "title": "Exchange Rates API",
    "version": "1.0",
    "contact": {
      "name": "Madis Väin"
    },
    "description": "Fastest exchange rates API\nThe most scalable API for current and historical\nexchange rates with unmatched performance\nFast & reliable API built for developers – easy to setup super lightweight ",
    "x-logo": {
      "url": "https://exchangeratesapi.io/assets/images/exchangeratesapi_shortcut_icon.ico"
    }
  },
  "servers": [
    {
      "url": "https://api.exchangeratesapi.io/v1"
    },
    {
      "url": "http://api.exchangeratesapi.io/v1"
    }
  ],
  "paths": {
    "/latest": {
      "get": {
        "summary": "Get the latest exchange rates",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/rates"
                },
                "examples": {
                  "example": {
                    "value": {
                      "rates": {
                        "CAD": 1.5476,
                        "HKD": 9.4274,
                        "ISK": 155,
                        "PHP": 58.417,
                        "DKK": 7.4421,
                        "HUF": 353.63,
                        "CZK": 26.317,
                        "AUD": 1.6064,
                        "RON": 4.8707,
                        "SEK": 10.193,
                        "IDR": 17216.41,
                        "INR": 89.4505,
                        "BRL": 6.1237,
                        "RUB": 88.7888,
                        "HRK": 7.529,
                        "JPY": 126.11,
                        "THB": 36.583,
                        "CHF": 1.0776,
                        "SGD": 1.6202,
                        "PLN": 4.4373,
                        "BGN": 1.9558,
                        "TRY": 9.5728,
                        "CNY": 7.9588,
                        "NOK": 10.5833,
                        "NZD": 1.7101,
                        "ZAR": 18.2339,
                        "USD": 1.2162,
                        "MXN": 24.3753,
                        "ILS": 3.9614,
                        "GBP": 0.907,
                        "KRW": 1327.5,
                        "MYR": 4.9299
                      },
                      "base": "EUR",
                      "date": "2020-12-14"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-latest",
        "description": "Get the latest foreign exchange reference rates.",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "base",
            "description": "Rates are quoted against the Euro by default. Quote against a different currency by setting the base parameter in your request."
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "symbols",
            "description": "Request specific exchange rates by setting the symbols parameter."
          }
        ],
        "cache": {
          "expire": "604800",
          "public": true
        }
      }
    },
    "/{date}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "date",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Get exchange rates for a specific day",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/rates"
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "rates": {
                        "CAD": 0,
                        "HKD": 0,
                        "ISK": 0,
                        "PHP": 0,
                        "DKK": 0,
                        "HUF": 0,
                        "CZK": 0,
                        "AUD": 0,
                        "RON": 0,
                        "SEK": 0,
                        "IDR": 0,
                        "INR": 0,
                        "BRL": 0,
                        "RUB": 0,
                        "HRK": 0,
                        "JPY": 0,
                        "THB": 0,
                        "CHF": 0,
                        "SGD": 0,
                        "PLN": 0,
                        "BGN": 0,
                        "TRY": 0,
                        "CNY": 0,
                        "NOK": 0,
                        "NZD": 0,
                        "ZAR": 0,
                        "USD": 0,
                        "MXN": 0,
                        "ILS": 0,
                        "GBP": 0,
                        "KRW": 0,
                        "MYR": 0
                      },
                      "base": "string",
                      "date": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-date",
        "description": "Get historical rates for any day since 1999.",
        "cache": {
          "expire": "604800",
          "public": true
        }
      }
    }
  },
  "components": {
    "schemas": {
      "rates": {
        "description": "",
        "type": "object",
        "properties": {
          "rates": {
            "type": "object",
            "properties": {
              "CAD": {
                "type": "number"
              },
              "HKD": {
                "type": "number"
              },
              "ISK": {
                "type": "number"
              },
              "PHP": {
                "type": "number"
              },
              "DKK": {
                "type": "number"
              },
              "HUF": {
                "type": "number"
              },
              "CZK": {
                "type": "number"
              },
              "AUD": {
                "type": "number"
              },
              "RON": {
                "type": "number"
              },
              "SEK": {
                "type": "number"
              },
              "IDR": {
                "type": "number"
              },
              "INR": {
                "type": "number"
              },
              "BRL": {
                "type": "number"
              },
              "RUB": {
                "type": "number"
              },
              "HRK": {
                "type": "number"
              },
              "JPY": {
                "type": "number"
              },
              "THB": {
                "type": "number"
              },
              "CHF": {
                "type": "number"
              },
              "SGD": {
                "type": "number"
              },
              "PLN": {
                "type": "number"
              },
              "BGN": {
                "type": "number"
              },
              "TRY": {
                "type": "number"
              },
              "CNY": {
                "type": "number"
              },
              "NOK": {
                "type": "number"
              },
              "NZD": {
                "type": "number"
              },
              "ZAR": {
                "type": "number"
              },
              "USD": {
                "type": "number"
              },
              "MXN": {
                "type": "number"
              },
              "ILS": {
                "type": "number"
              },
              "GBP": {
                "type": "number"
              },
              "KRW": {
                "type": "number"
              },
              "MYR": {
                "type": "number"
              }
            },
            "required": [
              "CAD",
              "HKD",
              "ISK",
              "PHP",
              "DKK",
              "HUF",
              "CZK",
              "AUD",
              "RON",
              "SEK",
              "IDR",
              "INR",
              "BRL",
              "RUB",
              "HRK",
              "JPY",
              "THB",
              "CHF",
              "SGD",
              "PLN",
              "BGN",
              "TRY",
              "CNY",
              "NOK",
              "NZD",
              "ZAR",
              "USD",
              "MXN",
              "ILS",
              "GBP",
              "KRW",
              "MYR"
            ]
          },
          "base": {
            "type": "string",
            "minLength": 1
          },
          "date": {
            "type": "string",
            "minLength": 1
          }
        },
        "required": [
          "rates",
          "base",
          "date"
        ],
        "x-examples": {
          "example": {
            "rates": {
              "CAD": 1.5476,
              "HKD": 9.4274,
              "ISK": 155,
              "PHP": 58.417,
              "DKK": 7.4421,
              "HUF": 353.63,
              "CZK": 26.317,
              "AUD": 1.6064,
              "RON": 4.8707,
              "SEK": 10.193,
              "IDR": 17216.41,
              "INR": 89.4505,
              "BRL": 6.1237,
              "RUB": 88.7888,
              "HRK": 7.529,
              "JPY": 126.11,
              "THB": 36.583,
              "CHF": 1.0776,
              "SGD": 1.6202,
              "PLN": 4.4373,
              "BGN": 1.9558,
              "TRY": 9.5728,
              "CNY": 7.9588,
              "NOK": 10.5833,
              "NZD": 1.7101,
              "ZAR": 18.2339,
              "USD": 1.2162,
              "MXN": 24.3753,
              "ILS": 3.9614,
              "GBP": 0.907,
              "KRW": 1327.5,
              "MYR": 4.9299
            },
            "base": "EUR",
            "date": "2020-12-14"
          }
        }
      }
    },
    "securitySchemes": {
      "access_key": {
        "name": "access_key",
        "type": "apiKey",
        "in": "query"
      }
    }
  },
  "tags": [
    {
      "name": "Exchange rates"
    }
  ],
  "security": [
    {
      "access_key": []
    }
  ]
}